{{- if .Values.postgresql.onepassword.enabled -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.postgresql.onepassword.secretName | default (printf "%s-postgresql-onepassword" .Release.Name) }}
  labels:
    {{- include "postgresql-cluster.labels" . | nindent 4 }}
spec:
  itemPath: "vaults/{{ .Values.postgresql.onepassword.vault }}/items/{{ .Values.postgresql.onepassword.item }}"
{{- end -}}
