apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus-db
  namespace: cnpg-system
spec:
  interval: 1h
  releaseName: gatus-db
  targetNamespace: cnpg-system
  
  chartRef:
    kind: HelmChart
    name: postgresql-cluster
    namespace: flux-system
  
  install:
    createNamespace: false
    remediation: 
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  values:
    nameOverride: gatus-db

    instances: 3

    postgresql:
      database:
        name: gatus
        owner: gatus
      onepassword:
        enabled: true
        item: "[Database] Gatus"
        secretName: gatus-db
    
    storage:
      size: 3Gi
      storageClass: "longhorn-default-sc"
    
    loadBalancer:
      hostname: "gatus-db.from-gondor.com"
      ipPool: "homelab-database-pool"

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 192Mi
