apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.homelab.lan
    metallb.io/ip-allocated-from-pool: homelab-local-pool
    metallb.universe.tf/allow-shared-ip: longhorn-svc
