apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshot
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 30 20 * * ?
  groups:
  - default
  labels:
    backup-frequence: daily
    category: apps
  name: daily-snapshot
  parameters: {}
  retain: 1
  task: snapshot
