apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - "namespace.yaml"
 - "repository.yaml"
 - "release.yaml"
 - "storage-classes.yaml"
 - "daily-snapshot.yaml"
 - "weekly-backup.yaml"
 - "weekly-volume-backup.yaml"
