---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h # for drifting resources
  releaseName: longhorn
  targetNamespace: longhorn-system
  chart:
    spec:
      #renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.9.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              namespace: longhorn-system
              labelSelector: "app=longhorn-ui"
            patch: |-
              - op: add
                path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
                value: longhorn.homelab.lan
              - op: add
                path: /metadata/annotations/metallb.io~1ip-allocated-from-pool
                value: homelab-local-pool

  values:
    longhornUI:
      replicas: 1
    service:
      ui:
        type: "LoadBalancer"
        loadBalancerIP: 192.168.68.202
    defaultSettings:
      defaultDataPath: "/var/mnt/storage"
    defaultBackupStore:
      backupTarget: "nfs://192.168.68.120:/backups"
      pollInterval: 500
    persistence:
      defaultClass: "longhorn-default-sc"
    preUpgradeChecker:
      # Disabling it since upgrades are done by fluxcd as per:
      # "Disable this setting when installing Longhorn using Argo CD or other GitOps solutions."
      jobEnabled: false
