---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h # for drifting resources
  releaseName: longhorn
  targetNamespace: longhorn-system
  chart:
    spec:
      #renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.10.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    longhornUI:
      replicas: 1
    service:
      ui:
        type: "LoadBalancer"
        loadBalancerIP: 192.168.68.202
        annotations:
          external-dns.alpha.kubernetes.io/hostname: longhorn.homelab.lan
          metallb.io/ip-allocated-from-pool: homelab-local-pool
    defaultSettings:
      defaultDataPath: "/var/mnt/storage"
    defaultBackupStore:
      backupTarget: "nfs://192.168.68.120:/backups"
      pollInterval: 500
    persistence:
      defaultClass: "longhorn-default-sc"
    preUpgradeChecker:
      # Disabling it since upgrades are done by fluxcd as per:
      # "Disable this setting when installing Longhorn using Argo CD or other GitOps solutions."
      jobEnabled: false
