---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h # for drifting resources
  releaseName: longhorn
  targetNamespace: longhorn-system
  chart:
    spec:
      chart: longhorn
      version: 1.9.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    longhornUI:
      replicas: 1
    defaultBackupStore:
      backupTarget: "nfs://192.168.68.120:/backups"
      pollInterval: 500

