apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-system-backup
  namespace: longhorn-system
spec:
  concurrency: 0
  cron: 30 6 * * MON
  groups:
    - default
  labels:
    backup-frequence: weekly
    category: system
  name: weekly-system-backup
  parameters:
    volume-backup-policy: if-not-present
  retain: 1
  task: system-backup
