apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal-ingress-release
  namespace: ingress-nginx
spec:
  interval: 1h # for drifting resources
  releaseName: internal-ingress
  targetNamespace: ingress-nginx
  chart:
    spec:
      #renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.14.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    namespaceOverride: "ingress-nginx"
    controller:
      replicaCount: 4
      minAvailable: 2
      ingressClass: internal-ingress
      ingressClassResource:
        name: internal-ingress
    defaultBackend:
      enabled: true
      replicaCount: 1
