{{- if .Values.onepassword.enabled -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onepassword.secretName | default (printf "%s-onepassword" .Release.Name) }}
  labels:
    {{- include "one-chart.labels" . | nindent 4 }}
spec:
  itemPath: "vaults/{{ .Values.onepassword.vault }}/items/{{ .Values.onepassword.item }}"
{{- end -}}
