{{- if .Values.onepassword.enabled -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onepassword.secretName | default (printf "%s-onepassword" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.onepassword.vault }}/items/{{ .Values.onepassword.item }}"
{{- end -}}
