apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: one-chart
  namespace: flux-system
spec:
  interval: 12h
  chart: one-chart
  version: '0.1.x'
  sourceRef:
    kind: HelmRepository
    name: homelab
---