apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: one-chart
  namespace: flux-system
spec:
  #renovate: registryUrl=oci://ghcr.io/josimar-silva/homelab
  chart: one-chart
  version: 0.5.1
  interval: 12h
  sourceRef:
    kind: HelmRepository
    name: homelab
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: postgresql
  namespace: flux-system
spec:
  #renovate: registryUrl=oci://registry-1.docker.io/bitnamicharts
  chart: postgresql
  version: 16.7.15
  interval: 12h
  sourceRef:
    kind: HelmRepository
    name: bitnami
