apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  type: "oci"
  url: oci://ghcr.io/josimar-silva/homelab
  interval: 24h
  timeout: 5m
  secretRef:
    name: homelab-oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  type: "oci"
  url: oci://registry-1.docker.io/bitnamicharts
  interval: 24h
  timeout: 5m
