---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-release
  namespace: ollama
spec:
  interval: 1h # for drifting resources
  releaseName: ollama
  targetNamespace: ollama
  chart:
    spec:
      chart: ollama
      version: 1.26.0
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: otwld
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: "ollama/ollama"
      tag: "0.11.7"

    replicaCount: 1

    nodeSelector:
      middle-earth-cluster.from-gondor.com/category: hobbit-bg-i7

    persistentVolume:
      enabled: true
      storageClass: "longhorn-default-sc"
      size: 30Gi

    resources:
      limits:
        cpu: 2000m
        memory: 4096Mi
      requests:
        cpu: 500m
        memory: 2000Mi
    
    ingress:
      enabled: false

    ollama:
      models:
        clean: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-release
  namespace: ollama
spec:
  interval: 1h
  releaseName: openwebui
  targetNamespace: ollama
  dependsOn:
    - name: ollama-release
  chart:
    spec:
      chart: open-webui
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    image:
      repository: "ghcr.io/open-webui/open-webui"
      tag: "main"

    replicaCount: 1

    ingress:
      enabled: true
      class: internal-ingress
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
      host: chat.from-gondor.com
      tls: true

    persistence:
      storageClass: "longhorn-default-sc"
      size: 2Gi

    ollama:
      enabled: false

    pipelines:
      enabled: false
      
    ollamaUrls:
      - http://ollama.ollama.svc.cluster.local:11434
