apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-release
  namespace: ollama
spec:
  interval: 1h
  releaseName: openwebui
  targetNamespace: ollama
  chart:
    spec:
      #renovate: registryUrl=https://helm.openwebui.com
      chart: open-webui
      version: 12.5.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    image:
      repository: "ghcr.io/open-webui/open-webui"
      tag: "v0.8.5"

    replicaCount: 1

    ingress:
      enabled: false

    persistence:
      storageClass: "longhorn-default-sc"
      size: 10Gi

    resources:
      limits:
        cpu: 2
        memory: 3Gi
      requests:
        cpu: 900m
        memory: 2Gi

    ollama:
      enabled: false

    pipelines:
      enabled: false
      
    ollamaUrls:
      - http://smaug.smaug.svc.cluster.local:11434
