apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: cert-manager
spec:
  interval: 1h # for drifting resources
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      #renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.17.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
    replicaCount: 4
    podDisruptionBudget:
      enabled: true
      minAvailable: 2
    enableCertificateOwnerRef: true
