apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden-db
  namespace: cnpg-system
spec:
  interval: 1h
  releaseName: linkwarden-db
  targetNamespace: cnpg-system
  
  chartRef:
    kind: HelmChart
    name: postgresql-cluster
    namespace: flux-system
  
  install:
    createNamespace: false
    remediation: 
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  values:
    nameOverride: linkwarden-db

    instances: 1

    postgresql:
      database:
        name: linkwarden
        owner: linkwarden
      onepassword:
        enabled: true
        item: "[Database] Linkwarden"
        secretName: linkwarden-db
    
    storage:
      size: 2Gi
      storageClass: "longhorn-database-sc"

    loadBalancer:
      hostname: "linkwarden-db.from-gondor.com"
      ipPool: "homelab-database-pool"

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
