apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 2h
  retryInterval: 5m
  timeout: 5m
  path: ./infrastructure/rivendell
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
