apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: node-local-dns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/component: dns
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: node-local-dns
