apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-local-dns
  labels:
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/component: dns
rules:
# NodeLocal DNS needs to read ConfigMaps for dynamic config updates
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Read endpoints for service discovery
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["list", "watch"]
# Read services for upstream DNS discovery
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-local-dns
  labels:
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/component: dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-local-dns
subjects:
- kind: ServiceAccount
  name: node-local-dns
  namespace: kube-system
