apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-local-dns
  namespace: kube-system
  labels:
    prometheus: kube-prometheus-stack
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/component: dns
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: node-local-dns
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
      relabelings:
        # Add node name as a label for better visibility
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
          action: replace
        # Add pod name
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
          action: replace
        # Add namespace
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
          action: replace
