apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-backups-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
    - rsize=1048576
    - wsize=1048576
  nfs:
    server: 192.168.68.120
    path: /backups/cnpg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnpg-backups-nfs-pvc
  namespace: cnpg-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: cnpg-backups-nfs-pv
  resources:
    requests:
      storage: 100Gi
