apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 1h # for drifting resources
  releaseName: onepassword-connect
  targetNamespace: onepassword
  chart:
    spec:
      #renovate: registryUrl=https://1password.github.io/connect-helm-charts
      chart: connect
      version: 2.0.0
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    connect:
      applicationName: onepassword-connect
      credentialsName: onepassword-credentials
      credentialsKey: 1password-credentials.json
      annotations:
        homelab.category: secret-management
        homelab.realm: security
    operator:
      create: true
      applicationName: onepassword-operator
      autoRestart: true
      serviceAccountToken:
        name: onepassword-credentials
        key: 1password-service-account
      annotations:
        homelab.category: secret-management
        homelab.realm: security
