apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 1h # for drifting resources
  releaseName: onepassword-connect
  targetNamespace: onepassword
  chart:
    spec:
      #renovate: registryUrl=https://1password.github.io/connect-helm-charts
      chart: connect
      version: 2.0.3
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  # This is a workaround to set the operator service account token 
  # from a Secret, as the Helm chart does not support it directly.
  valuesFrom:
    - kind: Secret
      name: onepassword-credentials
      valuesKey: 1password-service-account
      targetPath: operator.serviceAccountToken.value

  values:
    connect:
      applicationName: onepassword-connect
      credentialsName: onepassword-credentials
      credentialsKey: 1password-credentials.json
      annotations:
        homelab.category: secret-management
        homelab.realm: security
    operator:
      create: true
      applicationName: onepassword-operator
      autoRestart: true
      pollingInterval: 1800
      # serviceAccountToken:
        # value: "set by fluxcd from a secret"
      annotations:
        homelab.category: secret-management
        homelab.realm: security
