apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: flux-system
spec:
  url: https://1password.github.io/connect-helm-charts
  interval: 24h
  timeout: 5m
