apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-local-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.68.201-192.168.68.200
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-database-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.68.201-192.168.68.250
