apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h # for drifting resources
  releaseName: metallb
  targetNamespace: metallb
  chart:
    spec:
      chart: metallb
      version: "0.14.9"
      interval: 5h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    controller:
      image:
        repository: quay.io/metallb/controller
        tag: "v0.14.9"
    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: "v0.14.9"
