apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1h # for drifting resources
  releaseName: metallb
  targetNamespace: metallb
  chart:
    spec:
      #renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: "0.15.3"
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      image:
        repository: quay.io/metallb/controller
    speaker:
      image:
        repository: quay.io/metallb/speaker
