apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 1h # Check for drift every hour
  releaseName: trivy-operator
  targetNamespace: trivy-system
  chart:
    spec:
      #renovate: registryUrl=https://aquasecurity.github.io/helm-charts/
      chart: trivy-operator
      version: 0.32.0
      interval: 12h # Check for new chart versions every 12 hours
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system

  install:
    createNamespace: false
    remediation:
      retries: 3
    crds: CreateReplace # Install CRDs during installation

  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace # Update CRDs during upgrades
    cleanupOnFail: true

  uninstall:
    keepHistory: false

  values:
    # Common labels for all resources
    commonLabels:
      cluster: middle-earth-cluster

    # Namespace override
    namespaceOverride: trivy-system

    # ============================================
    # Pod Security Context (root level - for operator deployment)
    # Required for restricted PSS namespace
    # NOTE: These settings apply to the trivy-operator deployment pod
    # ============================================
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10000
      runAsGroup: 10000
      fsGroup: 10000
      seccompProfile:
        type: RuntimeDefault

    # ============================================
    # Container Security Context (root level - for operator container)
    # Required for restricted PSS namespace
    # NOTE: These settings apply to the trivy-operator container
    # ============================================
    securityContext:
      runAsNonRoot: true
      runAsUser: 10000
      runAsGroup: 10000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    # ============================================
    # Trivy Operator Configuration
    # ============================================
    trivy:
      # Ignore vulnerabilities without available fixes to reduce noise
      ignoreUnfixed: true

      # Severity threshold for vulnerability detection
      severity: CRITICAL,HIGH,MEDIUM

      # Resource limits for Trivy scanner jobs
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # ============================================
    # Operator Configuration
    # ============================================
    operator:
      # Resource limits for the operator itself
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi

      # Replicas for HA
      replicas: 1

      # ----------------------------------------
      # Scan frequency settings (reduce cluster load)
      # ----------------------------------------
      # Max concurrent scan jobs (default: 10)
      scanJobsConcurrentLimit: 3
      # Max concurrent node collector jobs (default: 1)
      scanNodeCollectorLimit: 1
      # Delay between retrying failed scans (default: 30s)
      scanJobsRetryDelay: 60s
      # How long reports are valid before re-scanning (default: 24h)
      scannerReportTTL: "72h"
      # Cluster SBOM cache TTL (default: 120h)
      cacheReportTTL: "168h"

    # ============================================
    # Service Monitor Configuration
    # ============================================
    serviceMonitor:
      enabled: true
      # Add label to match Prometheus ServiceMonitor selector
      additionalLabels:
        prometheus: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s

    # ============================================
    # Scan Job Configuration (trivyOperator section)
    # ============================================
    trivyOperator:
      # Pod security context for scan jobs
      scanJobPodTemplatePodSecurityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      # Container security context for scan jobs
      scanJobPodTemplateContainerSecurityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

    # ============================================
    # Compliance and RBAC Scanning
    # ============================================
    compliance:
      enabled: true
      # Run compliance scans once daily at midnight (default: every 6 hours)
      cron: "0 0 * * *"

    rbacAssessment:
      enabled: true

    infraAssessment:
      enabled: true

    configAudit:
      enabled: true

    exposedSecretReport:
      enabled: true

    # ============================================
    # Vulnerability Report Configuration
    # ============================================
    vulnerabilityReports:
      scanner: Trivy

    # ============================================
    # Node Collector (DaemonSet)
    # ============================================
    # DISABLED: node-collector requires privileged access (hostPID=true, hostPath volumes)
    # which conflicts with the restricted PodSecurity policy enforced on trivy-system namespace.
    # This disables CIS Benchmark node-level compliance scanning but maintains all other
    # security scanning capabilities (vulnerabilities, config audits, RBAC assessment, etc.)
    # Re-enable only if you need node-level compliance scanning and can relax PSS to privileged.
    nodeCollector:
      enabled: false
      # Resource limits for node collector
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
