apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aqua
  namespace: flux-system
spec:
  type: "default"
  url: https://aquasecurity.github.io/helm-charts/
  interval: 24h
