apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-release
  namespace: homepage
spec:
  interval: 1h # for drifting resources
  releaseName: homepage
  targetNamespace: homepage
  chartRef:
    kind: HelmChart
    name: one-chart
    namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    homelab:
      category: apps
      realm: monitoring

    nameOverride: homepage

    serviceAccountName: homepage
    automountServiceAccountToken: true

    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.9.0

    replicaCount: 1

    strategy:
      type: Recreate

    onepassword:
      enabled: true
      vault: "Homelab"
      item: "Homepage"
      secretName: "homepage-secret"

    environmentVariables:
      fromSecret:
        enabled: true
        secrets:
          - homepage-secret

    dns:
      enabled: true
      policy: None
      config:
        nameservers:
          - 10.96.0.10
          - 192.168.68.201
          - 192.168.68.116
        searches:
          - homepage.homepage.svc.cluster.local
        options:
          - name: ndots
            value: '5'

    service:
      type: ClusterIP
      ports:
        - name: http
          port: 3000
          containerPort: 3000

    httpRoute:
      enabled: true
      parentRef:
        name: internal-gateway
        namespace: ingress-nginx
        sectionName: https-internal
      hostnames:
        - homepage.internal.from-gondor.com
      rules:
        - matches:
            - path: /
          port: 3000

    cloudflared:
      enabled: false

    podAnnotations:
      app.kubernetes.io/component: dashboard

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi

    livenessProbe:
      httpGet:
        path: /api/healthcheck
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10

    readinessProbe:
      httpGet:
        path: /api/healthcheck
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 10

    persistentVolumes:
      - name: config
        storageClass: "longhorn-default-sc"
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        mountPath: /app/config
      - name: logs
        storageClass: "longhorn-default-sc"
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        mountPath: /app/config/logs

    # Init container to ALWAYS copy config files from ConfigMap to PVC (source of truth)
    initContainers:
      - name: copy-config
        image: busybox:1.37
        command:
          - sh
          - -c
          - |
            echo "Copying configuration files from ConfigMap to PVC..."
            echo "ConfigMap is the source of truth - always overwriting config files"
            cp -v /tmp/configmap/* /app/config/
            chmod 644 /app/config/*.yaml
            echo "Configuration files copied successfully"
            echo "Current files in /app/config:"
            ls -la /app/config/
        volumeMounts:
          - name: homepage-config-source
            mountPath: /tmp/configmap
            readOnly: true
          - name: homepage-config
            mountPath: /app/config

    # Mount ConfigMap in init container only
    volumes:
      - name: homepage-config-source
        configMap:
          name: homepage-config
