apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-sync-config
  namespace: pihole
data:
  FULL_SYNC: "false"
  RUN_GRAVITY: "false"
  CRON: "*/10 * * * *"
  CLIENT_SKIP_TLS_VERIFICATION: "true"
  TZ: "Europe/Berlin"
  SYNC_CONFIG_DNS: "true"
  SYNC_CONFIG_DHCP: "false"
  SYNC_CONFIG_NTP: "true"
  SYNC_CONFIG_RESOLVER: "false"
  SYNC_CONFIG_DATABASE: "false"
  SYNC_CONFIG_MISC: "true"
  SYNC_CONFIG_DEBUG: "true"
  SYNC_GRAVITY_DHCP_LEASES: "false"
  SYNC_GRAVITY_GROUP: "false"
  SYNC_GRAVITY_AD_LIST: "true"
  SYNC_GRAVITY_AD_LIST_BY_GROUP: "true"
  SYNC_GRAVITY_DOMAIN_LIST: "true"
  SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: "true"
  SYNC_GRAVITY_CLIENT: "false"
  SYNC_GRAVITY_CLIENT_BY_GROUP: "false"
  API_ENABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-renewal-script
  namespace: pihole
data:
  renew-certs.sh: |
    #!/bin/sh

    set -e

    # The domain for which to renew the certificate
    DOMAIN="pihole.from-gondor.com"
    # The path to the acme.sh script
    ACME_SH_PATH="/root/.acme.sh/acme.sh"
    # The path to the Pi-hole configuration directory
    PIHOLE_CONFIG_DIR="/etc/pihole"
    # The path to the lighttpd configuration file
    LIGHTTPD_CONFIG_FILE="/etc/lighttpd/external.conf"

    # Check if acme.sh is installed
    if [ ! -f "$ACME_SH_PATH" ]; then
      echo "acme.sh not found. Please install it first."
      exit 1
    fi

    # Renew the certificate
    "$ACME_SH_PATH" --renew -d "$DOMAIN" --force

    # Install the certificate
    "$ACME_SH_PATH" --install-cert -d "$DOMAIN" \
      --cert-file "$PIHOLE_CONFIG_DIR/certs/pihole.pem" \
      --key-file "$PIHOLE_CONFIG_DIR/certs/pihole.key" \
      --fullchain-file "$PIHOLE_CONFIG_DIR/certs/pihole-fullchain.pem" \
      --reloadcmd "service lighttpd restart"

    # Create the combined certificate file for lighttpd
    cat "$PIHOLE_CONFIG_DIR/certs/pihole.key" "$PIHOLE_CONFIG_DIR/certs/pihole.pem" > "$PIHOLE_CONFIG_DIR/certs/pihole-combined.pem"

    # Update the lighttpd configuration
    if ! grep -q "ssl.pemfile" "$LIGHTTPD_CONFIG_FILE"; then
      echo "Updating lighttpd configuration"
      echo "ssl.pemfile = \"$PIHOLE_CONFIG_DIR/certs/pihole-combined.pem\"" >> "$LIGHTTPD_CONFIG_FILE"
      echo "ssl.ca-file = \"$PIHOLE_CONFIG_DIR/certs/pihole-fullchain.pem\"" >> "$LIGHTTPD_CONFIG_FILE"
      echo "ssl.engine = \"enable\"" >> "$LIGHTTPD_CONFIG_FILE"
      echo "ssl.cipher-list = \"EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH\"" >> "$LIGHTTPD_CONFIG_FILE"
    fi

    # Restart lighttpd
    service lighttpd restart
