apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pihole-credentials
  namespace: pihole
spec:
  itemPath: "vaults/Homelab/items/Pihole"
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: pihole
type: Opaque
data:
  id_rsa: <BASE64_ENCODED_PRIVATE_SSH_KEY>
