apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-release
  namespace: cnpg-system
spec:
  interval: 1h # for drifting resources
  releaseName: cnpg
  targetNamespace: cnpg-system
  chart:
    spec:
      #renovate: registryUrl=https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      version: 0.27.1
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      clusterWide: false
      data:
        INHERITED_ANNOTATIONS: middle-earth-cluster.homelab/*
        POSTGRES_IMAGE_NAME: quay.io/enterprisedb/postgresql:15.5
