apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flash-slothmore-release
  namespace: flash-slothmore
spec:
  interval: 1h # for drifting resources
  releaseName: flash-slothmore
  targetNamespace: flash-slothmore
  chartRef:
    kind: HelmChart
    name: one-chart
    namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    homelab:
      category: apps
      realm: automation

    nameOverride: flash-slothmore

    image:
      repository: "ghcr.io/josimar-silva/flash-slothmore"
      tag: "0.2.0"

    replicaCount: 1

    strategy:
      type: Recreate

    nodeSelector:
      middle-earth-cluster.from-gondor.com/category: hobbit-bg-i7

    service:
      type: ClusterIP
      port: 8080

    resources:
      limits:
        cpu: 500m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 100Mi

    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10

    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 10
