apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 1h
  releaseName: headlamp
  targetNamespace: headlamp
  chart:
    spec:
      #renovate: registryUrl=https://kubernetes-sigs.github.io/headlamp
      chart: headlamp
      version: 0.39.0
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    config:
      # Run in-cluster mode (use ServiceAccount token)
      inCluster: true
      baseURL: ""
      # Watch plugins for automatic reload
      watchPlugins: true

    # Enable plugin manager with Flux, Cert-Manager, and Trivy plugins
    pluginsManager:
      enabled: true
      configFile: "plugin.yml"
      configContent: |
        plugins:
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.5.0
          - name: cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
            version: 0.1.0
          - name: trivy
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_trivy
            version: 0.2.0
      # Security context for plugin manager - allow write access for npm operations
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        allowPrivilegeEscalation: false
        # Note: readOnlyRootFilesystem is NOT set to true here
        # The plugin manager needs writable /tmp for npm cache
        capabilities:
          drop:
            - ALL

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Use existing ServiceAccount with appropriate RBAC
    serviceAccount:
      create: true
      name: headlamp

    # Disable built-in ingress (using Gateway API HTTPRoute instead)
    ingress:
      enabled: false

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 100
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Volume mounts for writable directories
    # Note: The chart already mounts /headlamp/plugins with an emptyDir
    # We only need to add /tmp for npm cache and temp files
    volumeMounts:
      # Mount emptyDir for temporary files (npm cache, temp plugin installation)
      - name: tmp
        mountPath: /tmp

    # Volumes configuration
    volumes:
      # emptyDir for /tmp - ephemeral, recreated on pod restart
      # This is appropriate for temporary files and npm cache
      - name: tmp
        emptyDir: {}

    # Probes
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
