apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mend-renovate
  namespace: renovate
spec:
  interval: 1h # for drifting resources
  releaseName: mend-renovate-ce
  targetNamespace: renovate
  chart:
    spec:
      #renovate: registryUrl=https://mend.github.io/renovate-ce-ee
      chart: mend-renovate-ce
      version: 11.2.0
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: mend-renovate
        namespace: flux-system
  values:
    renovate:
      mendRnvAcceptTos: y
      mendRnvPlatform: github
      mendRnvGithubBotUserId: "215854695"
      mendRnvAutoDiscoverFilter: "josimar-silva/homelab,josimar-silva/homelab-landing-page,josimar-silva/blog,josimar-silva/flash-slothmore"
      existingSecret: mend-renovate
      logLevel: warn
      extraEnvVars:
        - name: MEND_RNV_DEBUG_MODE
          value: "true"
        - name: RENOVATE_AUTODISCOVER
          value: "true"
        - name: RENOVATE_GIT_AUTHOR
          value: "Radagast Bot <215854695+radagastbot[bot]@users.noreply.github.com>"
        - name: MEND_RNV_GITHUB_PEM_FILE_PATH
          value: "/usr/src/app/radagastbot/renovate.private-key.pem"
        - name: GHCR_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: ghcr-renovate-credentials
              key: username
        - name: GHCR_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ghcr-renovate-credentials
              key: password
      config: |
        module.exports = {
          "hostRules": [
            {
              "matchHost": "ghcr.io",
              "username": process.env.GHCR_REGISTRY_USERNAME,
              "password": process.env.GHCR_REGISTRY_PASSWORD
            }
          ]
        };
      
    podSecurityContext:
      fsGroup: 1000

    postgresql:
      enabled: true
      host: renovate-db-rw.cnpg-system.svc.cluster.local
      port: 5432
      database: renovate
      user: renovate

    cachePersistence:
      enabled: true
      storageClass: "longhorn-default-sc"
      size: 15Gi
    
    ingress:
      enabled: false

    extraVolumes:
      - name: github-radagastbot-pem
        secret:
          secretName: github-renovate-private-key

    extraVolumeMounts:
      - name: github-radagastbot-pem
        mountPath: /usr/src/app/radagastbot
        readOnly: true
