apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch-release
  namespace: linkwarden
spec:
  interval: 1h # for drifting resources
  releaseName: meilisearch
  targetNamespace: linkwarden
  chart:
    spec:
      #renovate: registryUrl=https://meilisearch.github.io/meilisearch-kubernetes
      chart: meilisearch
      version: 0.16.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: meilisearch
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "v1.12.8"
    existingMasterKeySecret: linkwarden-secret
    persistence:
      enabled: true
      storageClass: "longhorn-default-sc"
      size: "5Gi"
    service:
      type: ClusterIP
      port: 7700
    podLabels:
      homelab.category: database
      homelab.realm: search

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden-release
  namespace: linkwarden
spec:
  interval: 1h # for drifting resources
  releaseName: linkwarden
  targetNamespace: linkwarden
  dependsOn:
    - name: meilisearch-release
  chartRef:
    kind: HelmChart
    name: one-chart
    namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    homelab:
      category: apps
      realm: productivity

    nameOverride: linkwarden

    image:
      repository: "ghcr.io/linkwarden/linkwarden"
      tag: "v2.12.2"

    replicaCount: 1

    strategy:
      type: Recreate

    persistentVolume:
      enabled: true
      storageClass: "longhorn-default-sc"
      size: "5Gi"
      mountPath: /data/data
      accessModes:
        - ReadWriteOnce

    onepassword:
      enabled: true
      vault: "Homelab"
      item: "Linkwarden"
      secretName: "linkwarden-secret"

    environmentVariables:
      container:
        enabled: true
        variables:
          - name: NEXTAUTH_URL
            value: "https://linkwarden.from-gondor.com"
          - name: NEXT_PUBLIC_APP_URL
            value: "https://linkwarden.from-gondor.com"
          - name: NEXT_PUBLIC_DISABLE_SIGNUP
            value: "true"
          - name: NEXT_PUBLIC_DISABLE_REGISTRATION
            value: "true"
          - name: NEXT_PUBLIC_OLLAMA_ENDPOINT_URL
            value: "http://ollama.ollama.svc.cluster.local:11434"
          - name: NEXT_PUBLIC_OLLAMA_ENABLED
            value: "true"
          - name: OLLAMA_MODEL
            value: "phi4-mini:3.8b"
          - name: MEILI_HOST
            value: "http://meilisearch.linkwarden.svc.cluster.local:7700"
      fromSecret:
        enabled: true
        secrets:
          - linkwarden-secret

    service:
      type: ClusterIP
      port: 3000

    internalIngress:
      enabled: false

    cloudflared:
      enabled: true
      replicaCount: 1
      tunnel:
        name: linkwarden
        publicHostname: linkwarden.from-gondor.com
        localHostname: http://linkwarden.linkwarden.svc.cluster.local:3000
        originRequest:
          keepAliveTimeout: 4s
      onepassword:
        vault: Homelab
        item: "[Cloudflare Tunnel] Linkwarden"

    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1.5Gi

    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
