apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: terraform-db
  namespace: cnpg-system
spec:
  interval: 1h
  releaseName: terraform-db
  targetNamespace: cnpg-system
  
  chartRef:
    kind: HelmChart
    name: postgresql-cluster
    namespace: flux-system
  
  install:
    createNamespace: false
    remediation: 
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  values:
    nameOverride: terraform-db

    instances: 1

    postgresql:
      database:
        name: terraform
        owner: terraform
      onepassword:
        enabled: true
        item: "[Database] Terraform"
        secretName: terraform-db
    
    storage:
      size: 2Gi
      storageClass: "longhorn-default-sc"
    
    loadBalancer:
      hostname: "terraform-db.from-gondor.com"
      ipPool: "homelab-database-pool"

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 192Mi
