apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-dns

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: fluxcd
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configMapGenerator:
  - name: internal-dns-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

resources:
 - "namespace.yaml"
 - "repository.yaml"
 - "release.yaml"
