apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: internal-dns-release
  namespace: internal-dns
spec:
  interval: 1h # for drifting resources
  releaseName: internal-dns
  targetNamespace: internal-dns
  chart:
    spec:
      #renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      version: 1.17.x
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "v0.17.0"

  valuesFrom:
    - kind: ConfigMap
      name: internal-dns-values
