# Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
# You don't need to set this flag, but if you leave it unset, you will receive warning
# logs when ExternalDNS attempts to create TXT records.
registry: noop

# IMPORTANT: If you have records that you manage manually in Pi-hole, set
# the policy to upsert-only so they do not get deleted.
policy: upsert-only

namespaced: false

sources:
  - service
  - ingress

provider:
  name: pihole

env:
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    value: "http://192.168.68.201"
  - name: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
    value: "true"
  - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    value: "6"
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: internal-dns-pihole
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
