apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric-release
  namespace: ingress-nginx
spec:
  interval: 1h
  releaseName: nginx-gateway-fabric
  targetNamespace: ingress-nginx
  chart:
    spec:
      #renovate: registryUrl=oci://ghcr.io/nginx/charts
      chart: nginx-gateway-fabric
      version: 2.4.1
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nginxGateway:
      gatewayClassName: nginx
      gwAPIExperimentalFeatures:
        enable: false
    nginx:
      replicas: 2
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: homelab-local-pool
