apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-automated-ingest-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.68.120"
    path: "/ebooks"
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-automated-ingest-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: calibre-web-automated-ingest-pv

