apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatus

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: fluxcd
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configMapGenerator:
  - name: gatus-config
    files:
      - config.yaml=config.yaml

configurations:
  - kustomizeconfig.yaml

resources:
  - namespace.yaml
  - release.yaml
