apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus-release
  namespace: gatus
spec:
  interval: 1h # for drifting resources
  releaseName: gatus
  targetNamespace: gatus
  chart:
    spec:
      #renovate: registryUrl=https://twin.github.io/helm-charts
      chart: gatus
      version: 1.3.1
      interval: 12h # for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: twinproduction/gatus
      tag: v5.22.0

    labels:
      middle-earth-cluster.homelab/category: infrastructure
      middle-earth-cluster.homelab/realm: monitoring
    
    persistence:
      enabled: false
    
    serviceMonitor:
      enabled: true
    
    sidecarCtonainers:
      - name: cloudflared
        image: "cloudflare/cloudflared:2025.8.0"
        args:
          - tunnel
          - --config
          - /etc/cloudflared/config/config.yaml
          - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10

        ports:
          - containerPort: 2000
            name: http-metrics
        
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: gatus-secret
                key: TUNNEL_TOKEN
    
    config:
      storage:
        type: postgres
        path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gatus-db-rw.cnpg-system:5432/${POSTGRES_DB}?sslmode=disable"
      
      metrics: true

      ui:
        title: Gondor | Status
        header: Gondor
        logo: https://raw.githubusercontent.com/josimar-silva/homelab/refs/heads/main/docs/images/homelab-logo.png
        link: https://hello.from-gondor.com
        dark-mode: true
        buttons:
          - name: Homelab
            link: https://github.com/josimar-silva/homelab
          - name: Blog
            link: https://josimar-silva.com/blog
          - name: Github
            link: https://github.com/josimar-silva

      connectivity:
        checker:
          target: 1.1.1.1:53
          interval: 1m

      endpoints:
        - name: PgAdmin
          group: Internal
          type: http
          url: https://pgadmin.from-gondor.com/login
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Linkwarden
          group: Internal
          type: http
          url: https://linkwarden.from-gondor.com/
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Ollama
          group: Internal
          type: http
          url: https://chat.from-gondor.com
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Pi-hole Main
          group: Internal
          type: dns
          url: "192.168.68.201"
          interval: 1m
          dns:
            query-name: "from-gondor.com"
            query-type: "A"
          conditions:
            - "[DNS_RCODE] == NOERROR"     

        - name: Pi-hole Replica 01
          group: Internal
          type: http
          url: "192.168.68.116"
          interval: 1m
          dns:
            query-name: "from-gondor.com"
            query-type: "A"
          conditions:
            - "[DNS_RCODE] == NOERROR"     

        - name: Longhorn
          group: Internal
          type: http
          url: http://longhorn.homelab.lan/
          interval: 1m
          conditions:
            - "[STATUS] == 200"
        
        - name: Minas Tirith
          group: Internal
          type: http
          url: https://minas-tirith.homelab.lan
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Speedtest Tracker
          group: Internal
          type: http
          url: https://speedtest.from-gondor.com/admin/login
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: K8S dashboard
          group: Internal
          type: http
          url: https://k8s.from-gondor.com
          interval: 1m
          conditions:
            - "[STATUS] == 200"

        - name: Gondor Homepage
          group: External
          type: http
          url: https://hello.from-gondor.com
          interval: 30s
          conditions:
            - "[STATUS] == 200"
        
        - name: Gondor DNS
          group: External
          type: dns
          url: "1.1.1.1"
          interval: 5m
          dns:
            query-name: "from-gondor.com"
            query-type: "A"
          conditions:
            - "[DNS_RCODE] == NOERROR"
